### ISSUE TITLE
Usage Listview in reverse order

### ISSUE THREAD

**Issue by ray1984** [nicolasjafelle/PagingListView#11]
Is it possible to use PagingListView with reverse order (first items at the bottom, and loading at scrolling to top)?

**Comment by nicolasjafelle** [comment]
Sorry but not, that should be a kind of Pull-To-Refresh pattern with loading more items on top of it, this library does the opposite. Sorry!

**Comment by Morteza-Rastgoo** [comment]
I need this too, any suggestion?

**Comment by dmitrikudrenko** [comment]
@mori-honest, I can advice you that fork - https://github.com/krawa/PagingListView
