### ISSUE TITLE
loading animation not shown in fragment

### ISSUE THREAD

**Issue by falkontre** [nicolasjafelle/PagingListView#17]
Hi,

PagingListView, when used in a fragment, doesn't show the loading animation in the bottom of the list.
If used in an Activity, it's ok.

**Comment by nicolasjafelle** [comment]
Hi, no sorry. I think you are doing something wrong, can you paste the code? At least the lines where you  are using the PagingListView? Thanks!

**Comment by falkontre** [comment]
Hi, 

I'll try to be clearer about the scenario I'm in.

I'm using the new TabLayout, so I have two tabs, each one is a fragment which contains the PagingListView.

I've noticed that PaginListView.onFinishLoading is called with hasMoreItems = true, and that the footer View is correctly added to ListViev.... So when I scroll the list, I can see (sometimes) only some pixel of the upper part of the footer.

I figured that the view doesn't show because it's after the last visible element of list.

I've the same code in an activity and it works perfectly.

The fragment's code in which I load the data (from a JSON) in the adapter:

  public void onSuccess(int statusCode, Header[] headers, JSONArray productsJSON) {

```
                try {
                    GsonBuilder gsonBuilder = new GsonBuilder();
                    gsonBuilder.setDateFormat("dd/MM/yyyy hh:mm a");
                    Gson gson = gsonBuilder.create();
                    List<Product> products = Arrays.asList(gson.fromJson(productsJSON.toString(), Product[].class));
                    // if there is less entries than page size, stop loading
                    if (products.size() != PAGE_SIZE) {
                        hasMoreElements = false;
                        initialTextView.setVisibility(View.GONE);
                    } else {
                        pager++;
                        hasMoreElements = true;
                        initialTextView.setVisibility(View.GONE);
                    }
                    if (products.isEmpty()) {
                        initialTextView.setVisibility(View.VISIBLE);
                    }
                    listView.onFinishLoading(hasMoreElements, products);  <--- hasMoreElements = true
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
```

**Comment by falkontre** [comment]
this is the layout of the fragment....

If i put a space in the bottom, it works.

<RelativeLayout 

xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                tools:context="com.mysmartideas.falkontre.quantomicosti.activity.SearchRemoteProdottiActivity">

```
<com.paging.listview.PagingListView
    android:id="@android:id/list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_alignParentStart="false"
    android:layout_below="@+id/progressBar"
    android:layout_above="@+id/space" />

<ProgressBar
    android:id="@+id/progressBar"
    style="?android:attr/progressBarStyleLarge"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_alignParentTop="true"
    android:layout_centerHorizontal="true"
    android:layout_marginTop="200dp"
    android:indeterminate="true"
    android:visibility="gone"/>

<TextView
    android:id="@+id/tv_selectProduct"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_alignParentEnd="false"
    android:layout_alignParentStart="false"
    android:layout_centerHorizontal="true"
    android:layout_centerVertical="true"
    android:text="Nessun prodotto da visualizzare"
    android:textAppearance="?android:attr/textAppearanceMedium"/>

<Space
    android:layout_width="match_parent"
    android:layout_height="60dp"
    android:layout_alignParentBottom="true"
    android:layout_toEndOf="@+id/progressBar"
    android:id="@+id/space" />
```

</RelativeLayout>

**Comment by nicolasjafelle** [comment]
It seems the new TabLayout or the ViewPager is not computing the current height of the listView? Sounds a mismatch between the PagingListView and other component in the layout, that is why the android:layout_height="60dp" made the magic.

**Comment by falkontre** [comment]
It's right....I've opened an issue to google about this. Let's see what happen.
