### ISSUE TITLE
Crash on android 5

### ISSUE THREAD

**Issue by phantuanphong** [nicolasjafelle/PagingListView#18]
I notice crash when setHasMoreItems(true);

**Comment by nicolasjafelle** [comment]
Do you have a crashlog or something to check it? Thanks!

**Comment by phantuanphong** [comment]
I fixed, problem when you add and remove listview footer, you can check it.

 public void setHasMoreItems(boolean hasMoreItems) {
        this.hasMoreItems = hasMoreItems;
        setFooterDividersEnabled(false);
        if (!this.hasMoreItems) {
            //removeFooterView(loadingView);
            loadingView.setVisibility(View.GONE);
        } else if (findViewById(R.id.loading_view) == null) {
            addFooterView(loadingView);
            ListAdapter adapter = ((HeaderViewListAdapter) getAdapter()).getWrappedAdapter();
            setAdapter(adapter);
        }
    }

**Comment by phantuanphong** [comment]
I think you should remove loading textview just leaving Progress Bar because when background color is black, you can't see it
